Repository tokend/admin-panel, pull requests merged in 2019-05, with the labels that each got.

#80 [TDV-827] Fix issuance form confirmation
  CHANGELOG.md
  src/components/User/Assets/Issuance/components/IssuanceForm.vue
Labels: bug

#82 [TDV-823] Fix uploading asset docs
  CHANGELOG.md
  src/api/documents.js
  src/components/User/Assets/MasterAssets/components/AssetManager.vue
Labels: bug

#79 [TDV-745] KYC verification queue
  CHANGELOG.md
  src/api/responseHandlers/requests/ChangeRoleRequest.js
  src/components/App/filters/filters.js
  src/components/User/Assets/AssetRequests/AssetRequests.Show.vue
  src/components/User/KycRequests/KycRequests.Queue.vue
  src/components/User/KycRequests/KycRequests.vue
  src/components/User/KycRequests/queue/components/QueueRequestActions.vue
  src/components/User/KycRequests/queue/components/QueueRequestDocuments.vue
  src/components/User/KycRequests/queue/components/QueueRequestViewer.vue
  src/components/User/KycRequests/queue/components/ReviewDecisionViewer.vue
  src/components/User/KycRequests/queue/components/ReviewDecisionsList.vue
  src/components/User/KycRequests/queue/components/ReviewDecisionsListItem.vue
  src/components/User/KycRequests/queue/constants/decision-actions.js
  src/components/User/KycRequests/queue/constants/decision-states.js
  src/components/User/KycRequests/queue/wrappers/ReviewDecision.js
  src/components/User/Sales/components/SaleManager/SaleManager.SyndicateTab.vue
  src/components/User/Users/components/UserDetails/UserDetails.Kyc.vue
  src/components/User/Users/components/UserDetails/UserDetails.Request.vue
  src/components/User/Users/components/UserDetails/UserDetails.TasksManager.vue
  src/components/common/getters/UserDocGetter.vue
  src/components/common/getters/link_getter.mixin.js
  src/router/routes/UserRoutes.js
Labels: enhancement

#84 [TDV-674] Update price attributes on asset pair manager
  CHANGELOG.md
  src/components/User/Assets/AssetPairs/components/AssetPairCreator.vue
  src/components/User/Assets/AssetPairs/components/AssetPairManager.vue
  src/components/common/fields/InputField.vue
  src/components/common/fields/TickField.vue
  src/components/common/fields/scss/_fields-variables.scss
  src/components/common/fields/scss/input.scss
Labels: enhancement

#86 [TDV-903, TDV-650] Integrate Vuelidate
  CHANGELOG.md
  package.json
  src/components/App/components/VerifyTfa.vue
  src/components/Auth/Login/Login.vue
  src/components/Auth/Login/SeedLogin.vue
  src/components/Auth/Signup/Signup.vue
  src/components/User/Admins/components/AdminManager.vue
  src/components/User/Assets/AssetPairs/components/AssetPairCreator.vue
  src/components/User/Assets/AssetPairs/components/AssetPairManager.vue
  src/components/User/Assets/AssetRequests/components/AssetRequestRejectForm.vue
  src/components/User/Assets/Issuance/IssuanceDetails.vue
  src/components/User/Assets/Issuance/components/IssuanceForm.vue
  src/components/User/Assets/MasterAssets/components/AssetManager.vue
  src/components/User/Assets/Withdrawals/components/WithdrawalDetails.vue
  src/components/User/Fees/components/FeeForm.vue
  src/components/User/Fees/components/FeeList.vue
  src/components/User/KycRequests/queue/components/QueueRequestActions.vue
  src/components/User/Limits/Limits.Reviewer.vue
  src/components/User/Limits/components/Limits.Manager.vue
  src/components/User/Limits/components/Limits.UpdateForm.vue
  src/components/User/Sales/SaleRequests/components/SaleRequestManager/SaleRequestManager.vue
  src/components/User/Users/components/UserDetails/UserDetails.Block.vue
  src/components/User/Users/components/UserDetails/UserDetails.Request.vue
  src/components/User/Users/components/UserDetails/UserDetails.Reset.vue
  src/components/common/fields/InputField.vue
  src/components/common/fields/TextField.vue
  src/components/common/fields/scss/input.scss
  src/js/records/limits.record.js
  src/main.js
  src/mixins/form.mixin.js
  src/validators.js
  yarn.lock
Labels: bug, enhancement

#81 [TDV-427] Collected fees management
  CHANGELOG.md
  src/components/User/Fees/Fees.vue
  src/components/User/Fees/FeesBalances.Index.vue
  src/components/User/Fees/api.js
  src/components/User/Fees/components/CollectedFeesList.vue
  src/components/User/Fees/components/CollectedFeesWithdraw.vue
  src/components/User/Fees/components/CollectedFeesWithdrawals.vue
  src/components/common/fields/InputField.vue
  src/components/common/fields/SelectField.vue
  src/components/common/fields/scss/_fields-variables.scss
  src/components/common/fields/scss/input.scss
  src/components/common/formatters/AssetAmountFormatter.vue
  src/components/common/getters/EmailGetter.vue
  src/router/routes/UserRoutes.js
  src/store/index.js
  src/store/modules/assets.js
  src/store/modules/email-books.js
  src/store/modules/idle-handler.js
  src/store/wrappers/asset.js
  src/store/wrappers/balance.js
Labels: enhancement

#96 [TDQA-88] Fix pagination while loading limits
  CHANGELOG.md
  src/components/User/Limits/components/Limits.Manager.vue
Labels: bug
